services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/index.html:/app/index.html
    environment:
      DOCKER: "1"
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - server
